### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by huanghaiyang** [netless-io/fastboard#13]
index.js:1 Uncaught (in promise) Error: find invalid appIdentifier: undefined
    at zi2.parseAppIdentifier (index.js:1:1385969)
    at new zi2 (index.js:1:1376303)
    at createFastboard (FastboardApp.ts:586:15)
    at main.ts:8:1

**Comment by hyrious** [comment]
See [.env](https://github.com/netless-io/fastboard/blob/main/.env.example).
