### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'DEBUG')

### ISSUE THREAD

**Issue by ChurikiTenna** [netless-io/fastboard#14]
I am using:
- Nuxt3
- Typescript

When I call createFastboard, it return error below after '[White] join room success':
```
[Vue warn]: Unhandled error during execution of native event handler 
  at <Default > 
  at <AsyncComponentWrapper > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <Anonymous name="default" > 
  at <Live onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > key="/teachers/videos/GFIcfNwxS0fDTlB8YJuz" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
（匿名） @ runtime-core.esm-bundler.js:167
Promise.catch（非同期）
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
invoker @ runtime-dom.esm-bundler.js:369
index.js:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'DEBUG')
    at get isDebugEnabled [as isDebugEnabled] (index.js:200:14)
    at Emittery2.logIfDebugEnabled (index.js:233:16)
    at Emittery2.on (index.js:246:9)
    at index.js:274:21
    at new Promise (<anonymous>)
    at Emittery2.once (index.js:273:10)
    at new MainViewProxy (MainView.ts:25:17)
    at new AppManager (AppManager.ts:84:30)
    at _WindowManager.mount (index.ts:234:30)
    at async createFastboard (FastboardApp.ts:614:7)
get isDebugEnabled @ index.js:200
logIfDebugEnabled @ index.js:233
on @ index.js:246
（匿名） @ index.js:274
once @ index.js:273
MainViewProxy @ MainView.ts:25
AppManager @ AppManager.ts:84
mount @ index.ts:234
Promise.then（非同期）
MainViewProxy @ MainView.ts:25
AppManager @ AppManager.ts:84
mount @ index.ts:234
await in mount（非同期）
createFastboard @ FastboardApp.ts:614
await in createFastboard（非同期）
onWhiteboard @ [videoid].vue:349
await in onWhiteboard（非同期）
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
index.js:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'DEBUG')
    at get isDebugEnabled [as isDebugEnabled] (index.js:200:14)
    at Emittery2.logIfDebugEnabled (index.js:233:16)
    at Emittery2.on (index.js:246:9)
    at MainView.ts:35:28
    at r.add (side-effect-manager.ts:31:29)
    at new MainViewProxy (MainView.ts:34:32)
    at new AppManager (AppManager.ts:84:30)
    at _WindowManager.mount (index.ts:234:30)
    at async createFastboard (FastboardApp.ts:614:7)
    at async onWhiteboard ([videoid].vue:349:3)
```

Related code:
 ```
 const fastboard = await createFastboard({
    // [1]
    sdkConfig: {
      appIdentifier: "UgEUwBOZEe2cf2t-KTOIjQ/_KdJCGkT9cwAJQ",
      region: "us-sv",
    },
    // [2]
    joinRoom: {
      uid: "1",
      uuid: createRoomResult.uuid,
      roomToken: createRoomTokenResult,
    },
    // [3] (optional)
    managerConfig: {
      cursor: true,
    },
  });
```

I am not sure if it's a bug with sdk or my code.
If I need to provide more information, I am happy to do so.

**Comment by hyrious** [comment]
The error seems to come from [emittery](https://github.com/sindresorhus/emittery/blob/ca9ed93904970ff8b8ca1d3aaf441b663ab83441/index.js#L213), [which is a dependency of @netless/window-manager](https://github.com/netless-io/window-manager/blob/4addff577bcf4731793d5507b5d2c48e0732596d/package.json#L27), I'll paste related code here:

```js
// class Emittery {
	static get isDebugEnabled() {
		if (typeof process !== 'object') {
			return isGlobalDebugEnabled;
		}

		const {env} = process || {env: {}};
		return env.DEBUG === 'emittery' || env.DEBUG === '*' || isGlobalDebugEnabled;
	}
```

So it turns out that your project **injects an empty global `process` object** which leads to `process.env` becomes `undefined`. You may want to check whether you have enabled some plugins that polyfill node globals.
